---
title: "Alissa Power's Resume"
author: "Alissa Power"
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css: ['css/custom_resume.css', 'css/styles.css', 'resume']
    self_contained: true
---


```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)
library(tidyverse)
library(glue)

# Set this to true to have links turned into footnotes at the end of the document
PDF_EXPORT <- TRUE

# Holds all the links that were inserted for placement at the end
links <- c()

source('parsing_functions.R')


# First let's get the data, filtering to only the items tagged as
# Resume items
position_data <- read_csv('positions.csv') %>% 
  filter(in_resume) %>% 
  mutate(
    # Build some custom sections by collapsing others
    section = case_when(
      section %in% c('research_positions', 'industry_positions', 'sporting_positions') ~ 'positions', 
      section %in% c('data_science_writings', 'by_me_press') ~ 'writings',
      TRUE ~ section
    )
  ) 

```


Aside
================================================================================



Contact {#contact}
--------------------------------------------------------------------------------



- <i class="fa fa-envelope"></i> almowrey@asu.edu
- <i class="fa fa-github"></i> https://github.com/almowrey2026
- <i class="fa fa-phone"></i> (123) 456-7890



Technical Skills {#skills}
--------------------------------------------------------------------------------


```{r}
skills <- tribble(
  ~skill,                ~level,
  "R",                   3,
  "Data Analysis",       4,
  "Data Visualization",  4,
  "Project Management",  5,
  "Clinical Research",   5
)

build_skill_bars(skills)
```



Open Source Contributions {#open-source}
--------------------------------------------------------------------------------

Selected projects available on GitHub:

- `montyhall`: R package implementing and simulating the Monty Hall problem


Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made w/ [**pagedown**](https://github.com/rstudio/pagedown). 

[View source code on GitHub](https://github.com/almowrey2026/paf-514-cv-example).

Last updated on `r Sys.Date()`.




Main
================================================================================

Alissa Power {#title}
--------------------------------------------------------------------------------

```{r}
intro_text <- "Public health technology and clinical research leader with experience building scalable operational systems, data-driven performance frameworks, and AI-enabled tools across healthcare and clinical research.

Currently pursuing a Master of Public Health in Public Health Technology at Arizona State University, with interests in digital health, health informatics, applied AI/ML, and improving access to healthcare and clinical research."


cat(sanitize_links(intro_text))
```



Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
position_data %>% print_section('education')
```



Selected Positions {data-icon=suitcase}
--------------------------------------------------------------------------------

```{r}
position_data %>% print_section('positions')
```

Selected Projects {data-icon=laptop}
--------------------------------------------------------------------------------


```{r}
position_data %>% print_section('projects')
```


